### ISSUE TITLE
Crash during battle start

### ISSUE THREAD

**Issue by Romex91** [MShadowy/shadowyards#1]
88345 [Thread-4] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.IllegalStateException: Zero length vector
java.lang.IllegalStateException: Zero length vector
	at org.lwjgl.util.vector.Vector.normalise(Vector.java:91)
	at data.shipsystems.scripts.MS_mimirSlideDrive.apply(MS_mimirSlideDrive.java:127)
	at com.fs.starfarer.combat.systems.F.advance(Unknown Source)
	at com.fs.starfarer.combat.entities.Ship.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advanceInner(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Romex91** [comment]
I'm trying to fix it locally to be able to proceed with the campaign. But I never coded in JAVA, so I have problems opening the project.
@MShadowy, what IDE did you use?

**Comment by Romex91** [comment]
> I'm trying to fix it locally to be able to proceed with the campaign. But I never coded in JAVA, so I have problems opening the project.
> @MShadowy, what IDE did you use?

Nevermind, I managed to build it with Eclipse.  Thanks for modding this game:)

**Comment by MShadowy** [comment]
To the best of my ability to tell, this crash occurs basically as a result of the ship system being in an active state immediately as a battle is starting, hence why in every report I've received so far it's only occurred when joining a battle in which a Mimir is present. It ends up occurring very randomly as a result.

My best guess is that the root cause is that the ship tries to generate a Vector2f, but the combat engine isn't initialized so the vector returns a null and crashes the game. Alternatively it may be related to a memory leak I've resolved in the current dev release, in which the previous combat engine is kept in memory until the next battle, which may be resulting in the game trying to use improper data.
